// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/torderonex/load-balancer/internal/model"
)

// NewMockClientStorage creates a new instance of MockClientStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientStorage {
	mock := &MockClientStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientStorage is an autogenerated mock type for the ClientStorage type
type MockClientStorage struct {
	mock.Mock
}

type MockClientStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientStorage) EXPECT() *MockClientStorage_Expecter {
	return &MockClientStorage_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockClientStorage
func (_mock *MockClientStorage) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientStorage_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClientStorage_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClientStorage_Expecter) Close() *MockClientStorage_Close_Call {
	return &MockClientStorage_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClientStorage_Close_Call) Run(run func()) *MockClientStorage_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientStorage_Close_Call) Return(err error) *MockClientStorage_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientStorage_Close_Call) RunAndReturn(run func() error) *MockClientStorage_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteClient provides a mock function for the type MockClientStorage
func (_mock *MockClientStorage) DeleteClient(clientID string) error {
	ret := _mock.Called(clientID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClient")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(clientID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientStorage_DeleteClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClient'
type MockClientStorage_DeleteClient_Call struct {
	*mock.Call
}

// DeleteClient is a helper method to define mock.On call
//   - clientID
func (_e *MockClientStorage_Expecter) DeleteClient(clientID interface{}) *MockClientStorage_DeleteClient_Call {
	return &MockClientStorage_DeleteClient_Call{Call: _e.mock.On("DeleteClient", clientID)}
}

func (_c *MockClientStorage_DeleteClient_Call) Run(run func(clientID string)) *MockClientStorage_DeleteClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClientStorage_DeleteClient_Call) Return(err error) *MockClientStorage_DeleteClient_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientStorage_DeleteClient_Call) RunAndReturn(run func(clientID string) error) *MockClientStorage_DeleteClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllClientIDs provides a mock function for the type MockClientStorage
func (_mock *MockClientStorage) GetAllClientIDs() ([]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllClientIDs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientStorage_GetAllClientIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllClientIDs'
type MockClientStorage_GetAllClientIDs_Call struct {
	*mock.Call
}

// GetAllClientIDs is a helper method to define mock.On call
func (_e *MockClientStorage_Expecter) GetAllClientIDs() *MockClientStorage_GetAllClientIDs_Call {
	return &MockClientStorage_GetAllClientIDs_Call{Call: _e.mock.On("GetAllClientIDs")}
}

func (_c *MockClientStorage_GetAllClientIDs_Call) Run(run func()) *MockClientStorage_GetAllClientIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientStorage_GetAllClientIDs_Call) Return(strings []string, err error) *MockClientStorage_GetAllClientIDs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockClientStorage_GetAllClientIDs_Call) RunAndReturn(run func() ([]string, error)) *MockClientStorage_GetAllClientIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetClient provides a mock function for the type MockClientStorage
func (_mock *MockClientStorage) GetClient(clientID string) (*model.Client, bool) {
	ret := _mock.Called(clientID)

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 *model.Client
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (*model.Client, bool)); ok {
		return returnFunc(clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *model.Client); ok {
		r0 = returnFunc(clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(clientID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockClientStorage_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type MockClientStorage_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
//   - clientID
func (_e *MockClientStorage_Expecter) GetClient(clientID interface{}) *MockClientStorage_GetClient_Call {
	return &MockClientStorage_GetClient_Call{Call: _e.mock.On("GetClient", clientID)}
}

func (_c *MockClientStorage_GetClient_Call) Run(run func(clientID string)) *MockClientStorage_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClientStorage_GetClient_Call) Return(client *model.Client, b bool) *MockClientStorage_GetClient_Call {
	_c.Call.Return(client, b)
	return _c
}

func (_c *MockClientStorage_GetClient_Call) RunAndReturn(run func(clientID string) (*model.Client, bool)) *MockClientStorage_GetClient_Call {
	_c.Call.Return(run)
	return _c
}

// SaveClient provides a mock function for the type MockClientStorage
func (_mock *MockClientStorage) SaveClient(clientID string, client *model.Client) {
	_mock.Called(clientID, client)
	return
}

// MockClientStorage_SaveClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveClient'
type MockClientStorage_SaveClient_Call struct {
	*mock.Call
}

// SaveClient is a helper method to define mock.On call
//   - clientID
//   - client
func (_e *MockClientStorage_Expecter) SaveClient(clientID interface{}, client interface{}) *MockClientStorage_SaveClient_Call {
	return &MockClientStorage_SaveClient_Call{Call: _e.mock.On("SaveClient", clientID, client)}
}

func (_c *MockClientStorage_SaveClient_Call) Run(run func(clientID string, client *model.Client)) *MockClientStorage_SaveClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*model.Client))
	})
	return _c
}

func (_c *MockClientStorage_SaveClient_Call) Return() *MockClientStorage_SaveClient_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClientStorage_SaveClient_Call) RunAndReturn(run func(clientID string, client *model.Client)) *MockClientStorage_SaveClient_Call {
	_c.Run(run)
	return _c
}

// SetClientCapacity provides a mock function for the type MockClientStorage
func (_mock *MockClientStorage) SetClientCapacity(clientID string, capacity int) error {
	ret := _mock.Called(clientID, capacity)

	if len(ret) == 0 {
		panic("no return value specified for SetClientCapacity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = returnFunc(clientID, capacity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientStorage_SetClientCapacity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetClientCapacity'
type MockClientStorage_SetClientCapacity_Call struct {
	*mock.Call
}

// SetClientCapacity is a helper method to define mock.On call
//   - clientID
//   - capacity
func (_e *MockClientStorage_Expecter) SetClientCapacity(clientID interface{}, capacity interface{}) *MockClientStorage_SetClientCapacity_Call {
	return &MockClientStorage_SetClientCapacity_Call{Call: _e.mock.On("SetClientCapacity", clientID, capacity)}
}

func (_c *MockClientStorage_SetClientCapacity_Call) Run(run func(clientID string, capacity int)) *MockClientStorage_SetClientCapacity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockClientStorage_SetClientCapacity_Call) Return(err error) *MockClientStorage_SetClientCapacity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientStorage_SetClientCapacity_Call) RunAndReturn(run func(clientID string, capacity int) error) *MockClientStorage_SetClientCapacity_Call {
	_c.Call.Return(run)
	return _c
}

// SetClientRate provides a mock function for the type MockClientStorage
func (_mock *MockClientStorage) SetClientRate(clientID string, rate int) error {
	ret := _mock.Called(clientID, rate)

	if len(ret) == 0 {
		panic("no return value specified for SetClientRate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = returnFunc(clientID, rate)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientStorage_SetClientRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetClientRate'
type MockClientStorage_SetClientRate_Call struct {
	*mock.Call
}

// SetClientRate is a helper method to define mock.On call
//   - clientID
//   - rate
func (_e *MockClientStorage_Expecter) SetClientRate(clientID interface{}, rate interface{}) *MockClientStorage_SetClientRate_Call {
	return &MockClientStorage_SetClientRate_Call{Call: _e.mock.On("SetClientRate", clientID, rate)}
}

func (_c *MockClientStorage_SetClientRate_Call) Run(run func(clientID string, rate int)) *MockClientStorage_SetClientRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockClientStorage_SetClientRate_Call) Return(err error) *MockClientStorage_SetClientRate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientStorage_SetClientRate_Call) RunAndReturn(run func(clientID string, rate int) error) *MockClientStorage_SetClientRate_Call {
	_c.Call.Return(run)
	return _c
}
